common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: apt_manager_dev

test:
  <<: *common
  database: apt_manager_test

production:
  <<: *common
  database: apt_manager
